### ISSUE TITLE
google (unexpected crash CAPTCHA required

### ISSUE THREAD

**Issue by andrew6838** [unixfox/antibot-proxy#19]
Hi all,

google (unexpected crash CAPTCHA required

I got this error when search on page 3 or above, how to fix it?

https://github.com/unixfox/antibot-proxy
can antibot-proxy fix this error?

Thanks

**Comment by unixfox** [comment]
antibot-proxy doesn't fix that error, it only reduce the chance of having that error by stopping most of the bots.

Do note that it's only useful if you are running a public Searx instance, on a private instance it's useless to install it.
