### ISSUE TITLE
Only category: General showing results

### ISSUE THREAD

**Issue by Deon-Trevor** [unixfox/antibot-proxy#20]
Hello folks, SOS.

Not sure what I'm messing up in my setup but my SearXNG instance is only showing results for the general category. When I try to search for images, videos, news, etc on the GUI the buttons don't seem to work. Without the antibot-proxy, it works well. 

```https://searx.syncpundit.com/search?q=groot&language=en-US&time_range=&safesearch=0&theme=simple``` gives me a

 ```Rate limit exceeded```

Here's my config.toml:
```
COOKIE_NAME = 'searx'
ENDPOINT_NAME = 'searx.css'
HTML_TAG_REPLACE = '(<div id="pagination">)|(<head>)'
JAIL_PATH = '/home/searx-admin/jail'
MAX_RETRY = 5
PORT = 3030
TARGET = '127.0.0.1:4004'
TIMEOUT_LOAD = 120
WHITELIST = ['8.8.8.8', '1.1.1.1', '51.15.252.168']

[WHITELIST_PAGES]
GET = ['^/$', '^/autocompleter(.*)$', '^/favicon.ico$', '^/about$', '^/robots.txt$', '^/opensearch.xml$', '^/searx$']
POST = ['^/preferences$']
```

If there's anything I can do to help troubleshoot further please let me know

PS: the instance is public, only shared with friends and family

**Comment by unixfox** [comment]
This program is quite outdated, I recommend to switch to another one like https://github.com/asciimoo/filtron

Moreover you don't need antibot-proxy if your instance is just shared between your family.
